[supervisord]
nodaemon=true

[program:postgres]
command=/usr/local/bin/docker-entrypoint.sh postgres
user=postgres
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

[program:app]
#command=/bin/bash -le /app/app.sh
command=node dist/index.js --server
#conmmnad=bash -c "node dist/index.js --serve | tee -a /app/logs/app.log"
user=root
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

# [program:cron]
# command=bash -c "sleep 1 && /usr/sbin/cron -f"    # cron 需要添加 -f 参数确保处于前台运行
# process_name=%(program_name)s
# user=root
# autostart=true
# autorestart=true
# startretries=5
# exitcodes=0,2,70
# stopsignal=QUIT
# stopwaitsecs=2
# stdout_logfile=/var/log/supervisor/cron.log
